### ISSUE TITLE
cl-arrows is proprietary software

### ISSUE THREAD

**Issue by phoe** [alex-gutev/generic-cl#8] opened 2020-11-23 08:48 UTC
cl-arrows [does not have a license file](https://github.com/nightfly19/cl-arrows/issues/5) which makes it proprietary software.

Consider switching to another arrow macro library, such as [arrows](https://github.com/Harleqin/arrows), [arrow-macros](https://github.com/hipeta/arrow-macros), or (shameless plug) [binding-arrows](https://github.com/phoe/binding-arrows).

**Comment by alex-gutev** [comment] 2020-11-23 08:50
Duplicate of #5

**Closed by alex-gutev** 2020-11-23 08:50 UTC

**Comment by phoe** [comment] 2020-11-23 08:52
Woop - sorry about that. The changes have not yet been pulled into Quicklisp so I operated on stale data.
